sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.5.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  # wait until ActiveMQ is available
  - docker-compose run activemq-service wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 10 -O /dev/null http://admin:admin@activemq-service:8161/admin/
  # simple connection test from tclsh-service to activemq-service
  - docker-compose run --entrypoint /bin/sh tclsh-service -c "wget -O /dev/null http://admin:admin@activemq-service:8161/admin/"
  # run the test cases
  - docker-compose run --entrypoint tclsh8.6 -e stompServerURL=stomp://system:manager@activemq-service:61613 tclsh-service /opt/tcl/lib/tstomp/tStompTestIntegration.tcl
notifications:
  email:
    - derk@muenchhausen.de
