sudo: required
services:
  - docker

script:
  - docker run -d -e TZ=CEST -p 61613:61613 -p 127.0.0.1:8161:8161 rmohr/activemq:latest
  - docker ps -a
  - curl --retry 10 --retry-delay 5 -v -s -L -o /dev/null http://127.0.0.1:8161/
  - docker run -it -v ./:/opt/tcl/lib/tstomp -e stompServerURL=stomp://system:manager@127.0.0.1:61613 --rm efrecon/mini-tcl /opt/tcl/lib/tstomp/tStomp.test.tcl

notifications:
  email:
    - derk@muenchhausen.de
