sudo: required
services:
  - docker

script:
  - docker run -d -e TZ=CEST -p 61613:61613 -p 8161:8161 rmohr/activemq:latest
  - docker ps -a
  - echo $DOCKER_HOST
  - curl --retry 10 --retry-delay 5 -v -s -L -o /dev/null -u admin:admin http://localhost:8161/admin/
  - docker run -it -v ./:/opt/tcl/lib/tstomp -e stompServerURL=stomp://system:manager@localhost:61613 --rm efrecon/mini-tcl /opt/tcl/lib/tstomp/tStomp.test.tcl

notifications:
  email:
    - derk@muenchhausen.de
