activemq-service:
  image: rmohr/activemq:latest
  environment:
    - TZ=CEST
  ports:
    - "61613:61613"
    - "8161:8161"
  expose:
    - 61613
    - 8161

tclsh-service:
  build: .
  working_dir: /opt/tcl/lib/tstomp/
  environment:
    - TZ=CEST
  entrypoint: /bin/sh
  command: -c "echo 'puts stderr helloworld' | tclsh8.6"
  links:
    - activemq-service
